---

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    # there is no reason to test external files
    - "vendor/**/*"
    - "motbot.gemspec"
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true
  AllowSymlinksInCacheRootDirectory: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude: []
  ExcludedMethods:
    - describe
    - context
    - shared_examples

Layout/LineLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/Vagrantfile"
    - "Gemfile"
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
    - git
    - ftp
  IgnoreCopDirectives: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
