---
language: ruby
dist: bionic
rvm:
  - 2.6
cache: bundler
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_install:
  - pyenv global 3.7

  # Use bundler 2.x
  - gem install bundler

install:
  - npm install

  # XXX without this, pip3 fails with
  # `The `pip3' command exists in these Python versions:`
  - pip3 install --user yamllint ansible
  - bundle install --path=vendor/bundle --with development

  # XXX aspll for Ubuntu is too old. it does not support `--mode markdown`.
  # one day, ubuntu would catch up with us. see `test:aspell` in Rakefile.
  - aspell --version

scripts:
  - bundle exec rake test:ci
